"""Add post_offices table

Revision ID: 2ecfc39448e9
Revises: fdeacdf58376
Create Date: 2026-10-09 16:18:17.354852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ecfc39448e9'
down_revision: Union[str, Sequence[str], None] = 'fdeacdf58376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_offices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('pincode', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('division', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('mappingVersion', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_offices_name'), 'post_offices', ['name'], unique=False)
    op.create_index(op.f('ix_post_offices_pincode'), 'post_offices', ['pincode'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_offices_pincode'), table_name='post_offices')
    op.drop_index(op.f('ix_post_offices_name'), table_name='post_offices')
    op.drop_table('post_offices')
    # ### end Alembic commands ###
