/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParcelsRouteImport } from './routes/parcels'
import { Route as PostOfficesRouteImport } from './routes/post-offices'
import { Route as PredictionRouteImport } from './routes/prediction'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ParcelsParcelIdRouteImport } from './routes/parcels_.$parcelId'
import { Route as PostOfficesOfficeIdRouteImport } from './routes/post-offices_.$officeId'
import { Route as ReviewReviewIdRouteImport } from './routes/review_.$reviewId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcelsRoute = ParcelsRouteImport.update({
  id: '/parcels',
  path: '/parcels',
  getParentRoute: () => rootRouteImport,
} as any)
const PostOfficesRoute = PostOfficesRouteImport.update({
  id: '/post-offices',
  path: '/post-offices',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionRoute = PredictionRouteImport.update({
  id: '/prediction',
  path: '/prediction',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcelsParcelIdRoute = ParcelsParcelIdRouteImport.update({
  id: '/parcels_/$parcelId',
  path: '/parcels/$parcelId',
  getParentRoute: () => rootRouteImport,
} as any)
const PostOfficesOfficeIdRoute = PostOfficesOfficeIdRouteImport.update({
  id: '/post-offices_/$officeId',
  path: '/post-offices/$officeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewReviewIdRoute = ReviewReviewIdRouteImport.update({
  id: '/review_/$reviewId',
  path: '/review/$reviewId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/parcels': typeof ParcelsRoute
  '/post-offices': typeof PostOfficesRoute
  '/prediction': typeof PredictionRoute
  '/review': typeof ReviewRoute
  '/parcels/$parcelId': typeof ParcelsParcelIdRoute
  '/post-offices/$officeId': typeof PostOfficesOfficeIdRoute
  '/review/$reviewId': typeof ReviewReviewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/parcels': typeof ParcelsRoute
  '/post-offices': typeof PostOfficesRoute
  '/prediction': typeof PredictionRoute
  '/review': typeof ReviewRoute
  '/parcels/$parcelId': typeof ParcelsParcelIdRoute
  '/post-offices/$officeId': typeof PostOfficesOfficeIdRoute
  '/review/$reviewId': typeof ReviewReviewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/parcels': typeof ParcelsRoute
  '/post-offices': typeof PostOfficesRoute
  '/prediction': typeof PredictionRoute
  '/review': typeof ReviewRoute
  '/parcels_/$parcelId': typeof ParcelsParcelIdRoute
  '/post-offices_/$officeId': typeof PostOfficesOfficeIdRoute
  '/review_/$reviewId': typeof ReviewReviewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/parcels'
    | '/post-offices'
    | '/prediction'
    | '/review'
    | '/parcels/$parcelId'
    | '/post-offices/$officeId'
    | '/review/$reviewId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/parcels'
    | '/post-offices'
    | '/prediction'
    | '/review'
    | '/parcels/$parcelId'
    | '/post-offices/$officeId'
    | '/review/$reviewId'
  id:
    | '__root__'
    | '/'
    | '/parcels'
    | '/post-offices'
    | '/prediction'
    | '/review'
    | '/parcels_/$parcelId'
    | '/post-offices_/$officeId'
    | '/review_/$reviewId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ParcelsRoute: typeof ParcelsRoute
  PostOfficesRoute: typeof PostOfficesRoute
  PredictionRoute: typeof PredictionRoute
  ReviewRoute: typeof ReviewRoute
  ParcelsParcelIdRoute: typeof ParcelsParcelIdRoute
  PostOfficesOfficeIdRoute: typeof PostOfficesOfficeIdRoute
  ReviewReviewIdRoute: typeof ReviewReviewIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcels': {
      id: '/parcels'
      path: '/parcels'
      fullPath: '/parcels'
      preLoaderRoute: typeof ParcelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-offices': {
      id: '/post-offices'
      path: '/post-offices'
      fullPath: '/post-offices'
      preLoaderRoute: typeof PostOfficesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prediction': {
      id: '/prediction'
      path: '/prediction'
      fullPath: '/prediction'
      preLoaderRoute: typeof PredictionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcels_/$parcelId': {
      id: '/parcels_/$parcelId'
      path: '/parcels/$parcelId'
      fullPath: '/parcels/$parcelId'
      preLoaderRoute: typeof ParcelsParcelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-offices_/$officeId': {
      id: '/post-offices_/$officeId'
      path: '/post-offices/$officeId'
      fullPath: '/post-offices/$officeId'
      preLoaderRoute: typeof PostOfficesOfficeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review_/$reviewId': {
      id: '/review_/$reviewId'
      path: '/review/$reviewId'
      fullPath: '/review/$reviewId'
      preLoaderRoute: typeof ReviewReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ParcelsRoute: ParcelsRoute,
  PostOfficesRoute: PostOfficesRoute,
  PredictionRoute: PredictionRoute,
  ReviewRoute: ReviewRoute,
  ParcelsParcelIdRoute: ParcelsParcelIdRoute,
  PostOfficesOfficeIdRoute: PostOfficesOfficeIdRoute,
  ReviewReviewIdRoute: ReviewReviewIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
